# Generated by Django 5.2.12 on 2026-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_engine_car_mileage_car_name_car_price_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
    ]
